project_id = "iucogpdjtilkjpyxfgdb"

[functions.verify-access-code]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.send-reminders]
verify_jwt = false

[functions.annual-review]
verify_jwt = false

[functions.generate-access-code]
verify_jwt = false

[functions.extract-document]
verify_jwt = false